//! Ranged health collection (#467): planning without a `GraphSnapshot`,
//! per-range budgets and checkpoints, cross-range usage, determinism under
//! reordering and interruption, and the partial view.
//!
//! Every fixture is generated by `support/health_range_fixture.rs` (public,
//! synthetic, Go-shaped); the whole-snapshot analyzer is the control.

#[path = "support/health_range_fixture.rs"]
mod fixture;

use std::{
    cell::Cell,
    collections::{BTreeMap, BTreeSet},
};

use anyhow::{Context, Result};
use depgraph_core::{
    BlockerKind, CancellationToken, Confidence, FindingKind, HealthFinding,
    health::{
        HealthAnalysisError, analyze_unused_cancellable,
        range_checkpoint::HealthRangeCheckpointStore,
        ranged::{
            HealthExecutionMode, RangeOrder, RangedHealthError, RangedUnusedOptions,
            RangedUnusedOutcome, analyze_unused_ranged,
        },
    },
    service::{
        DepgraphCapabilitySet, DepgraphService, DepgraphServiceConfig, DepgraphServiceError,
        DepgraphServiceLimits, HealthFindingsRequest, HealthSummaryRequest, MAX_HEALTH_FINDINGS,
        SnapshotLocator, health_range_limits,
    },
};
use depgraph_store::{
    CountingHealthWorkBudget, HealthInputIdentity, HealthInputSelector, HealthLayer,
    HealthRangeLimits, HealthRangePlan, HealthWorkError, Store, health_work_error,
};
use fixture::{
    HealthRangeFixture, HealthRangeFixtureShape, expected_unused_counts, file_id, generate,
    symbol_id, symbol_is_called,
};

/// Test-only limits: the same shape as production, but a budget small enough
/// that the unit fixtures split into several ranges.
fn limits(per_range_work: u64) -> HealthRangeLimits {
    HealthRangeLimits {
        per_range_work,
        max_ranges: 4_096,
        planner_rows: 50_000_000,
        max_resplit_depth: 8,
    }
}

const SMALL_RANGE_BUDGET: u64 = 400;

fn open(fixture: &HealthRangeFixture) -> Result<Store> {
    Store::open_read_only(&fixture.store_path)
}

fn identity(store: &Store, fixture: &HealthRangeFixture) -> Result<HealthInputIdentity> {
    store.resolve_health_input(HealthInputSelector::CompletedSnapshot(&fixture.snapshot_id))
}

fn plan_for(
    store: &Store,
    fixture: &HealthRangeFixture,
    per_range_work: u64,
) -> Result<HealthRangePlan> {
    let identity = identity(store, fixture)?;
    store.health_range_plan(&identity, &limits(per_range_work), &mut || false)
}

fn whole_snapshot_findings(fixture: &HealthRangeFixture) -> Result<Vec<HealthFinding>> {
    let store = open(fixture)?;
    let snapshot = store.load_completed_snapshot(&fixture.snapshot_id)?;
    Ok(analyze_unused_cancellable(
        &snapshot,
        MAX_HEALTH_FINDINGS,
        usize::MAX,
        || false,
    )?)
}

fn ranged(
    store: &Store,
    fixture: &HealthRangeFixture,
    per_range_work: u64,
    order: RangeOrder,
    allow_partial: bool,
    checkpoints: Option<HealthRangeCheckpointStore>,
) -> Result<RangedUnusedOutcome, RangedHealthError> {
    let identity = identity(store, fixture).map_err(RangedHealthError::Store)?;
    analyze_unused_ranged(
        store,
        &identity,
        RangedUnusedOptions {
            limits: limits(per_range_work),
            maximum_findings: MAX_HEALTH_FINDINGS,
            allow_partial,
            order,
            checkpoints,
            progress: None,
        },
        || false,
    )
}

fn range_of<'p>(
    plan: &'p HealthRangePlan,
    subject_id: &str,
) -> Option<&'p depgraph_store::HealthRange> {
    plan.ranges.iter().find(|range| {
        range.first_subject_id.as_str() <= subject_id
            && subject_id <= range.last_subject_id.as_str()
    })
}

fn subject_ids(findings: &[HealthFinding]) -> BTreeSet<String> {
    findings
        .iter()
        .map(|finding| finding.subject_id.clone())
        .collect()
}

fn counts_by_confidence(findings: &[HealthFinding]) -> BTreeMap<Confidence, usize> {
    let mut counts = BTreeMap::new();
    for finding in findings {
        *counts.entry(finding.confidence).or_insert(0) += 1;
    }
    counts
}

fn assert_expected_unused(fixture: &HealthRangeFixture, findings: &[HealthFinding]) {
    let (expected_files, expected_symbols) = expected_unused_counts(&fixture.shape);
    let files = findings
        .iter()
        .filter(|finding| finding.kind == FindingKind::UnusedFile)
        .count();
    let symbols = findings
        .iter()
        .filter(|finding| finding.kind == FindingKind::UnusedExport)
        .count();
    assert_eq!((files, symbols), (expected_files, expected_symbols));
}

// --- Store API -----------------------------------------------------------

#[test]
fn resolve_health_input_of_a_completed_scan_is_one_plain_layer() -> Result<()> {
    let temporary = tempfile::tempdir()?;
    let fixture = generate(temporary.path(), &HealthRangeFixtureShape::small())?;
    let store = open(&fixture)?;
    let identity = identity(&store, &fixture)?;
    assert!(identity.is_plain());
    assert_eq!(
        identity.layers,
        vec![HealthLayer::Scan {
            scan_id: fixture.scan_id.clone(),
        }]
    );
    assert_eq!(
        identity.snapshot_id.as_deref(),
        Some(fixture.snapshot_id.as_str())
    );
    assert_eq!(identity.base_scan_id, fixture.scan_id);
    assert_eq!(identity.attempt_id, None);
    assert!(identity.layer_digest.starts_with("sha256:"));
    assert!(identity.staging_fingerprint.is_none());
    let error = store
        .resolve_health_input(HealthInputSelector::CompletedSnapshot("snapshot:missing"))
        .unwrap_err();
    assert!(error.to_string().contains("not found"), "{error:#}");
    Ok(())
}

#[test]
fn health_range_plan_uses_aggregates_only_and_is_deterministic() -> Result<()> {
    let temporary = tempfile::tempdir()?;
    let fixture = generate(temporary.path(), &HealthRangeFixtureShape::small())?;
    let store = open(&fixture)?;
    let first = plan_for(&store, &fixture, SMALL_RANGE_BUDGET)?;
    let second = plan_for(&store, &fixture, SMALL_RANGE_BUDGET)?;
    assert_eq!(first, second);
    assert!(first.plan_digest.starts_with("sha256:"));

    let shape = &fixture.shape;
    let subjects = (shape.packages * shape.files * (1 + shape.symbols)) as u64;
    assert_eq!(first.stats.subjects, subjects);
    assert_eq!(first.stats.nodes_by_kind["module"], shape.packages as u64);
    assert_eq!(first.stats.edges, fixture.edges);
    assert_eq!(first.stats.sites, fixture.sites);
    assert_eq!(first.stats.profiles, shape.profiles as u64);
    assert_eq!(first.stats.go_profiles, shape.profiles as u64);
    assert_eq!(first.stats.go_module_nodes, shape.packages as u64);
    assert_eq!(first.stats.targetless_sites, 0);
    assert_eq!(first.stats.ledger_incomplete_units, 0);

    // The planner reads sorted index scans and aggregates: one row per subject,
    // per distinct edge target, per site target, plus a handful of counts.
    assert!(first.planner_work_used <= limits(SMALL_RANGE_BUDGET).planner_rows);
    assert!(
        first.planner_work_used
            <= subjects + first.stats.edges + first.stats.site_targets + shape.packages as u64 + 64,
        "planner read {} rows",
        first.planner_work_used
    );

    // Ranges are disjoint, sorted, cover every subject, and each estimate is
    // below the budget.
    assert!(first.ranges.len() > 1, "{} ranges", first.ranges.len());
    assert_eq!(
        first
            .ranges
            .iter()
            .map(|range| range.subject_count)
            .sum::<u64>(),
        subjects
    );
    for (index, range) in first.ranges.iter().enumerate() {
        assert_eq!(range.index, index as u32);
        assert!(range.first_subject_id <= range.last_subject_id);
        if let Some(previous) = index.checked_sub(1).map(|i| &first.ranges[i]) {
            assert!(previous.last_subject_id < range.first_subject_id);
        }
        assert!(range.estimated_work <= SMALL_RANGE_BUDGET);
    }
    let inbound_edges = first
        .ranges
        .iter()
        .map(|range| range.inbound_edge_count)
        .sum::<u64>();
    let subject_inbound = shape.packages * shape.files * shape.profiles
        + shape.packages * shape.files * shape.symbols * shape.profiles;
    let call_edges = (0..shape.packages)
        .flat_map(|p| (0..shape.symbols).map(move |s| (p, s)))
        .filter(|&(p, s)| symbol_is_called(shape, p, s))
        .count()
        * shape.files
        * shape.profiles;
    assert_eq!(inbound_edges, (subject_inbound + call_edges) as u64);
    Ok(())
}

#[test]
fn health_range_plan_respects_max_ranges_and_planner_rows() -> Result<()> {
    let temporary = tempfile::tempdir()?;
    let fixture = generate(temporary.path(), &HealthRangeFixtureShape::small())?;
    let store = open(&fixture)?;
    let identity = identity(&store, &fixture)?;
    let error = store
        .health_range_plan(
            &identity,
            &HealthRangeLimits {
                max_ranges: 1,
                ..limits(SMALL_RANGE_BUDGET)
            },
            &mut || false,
        )
        .unwrap_err();
    assert_eq!(
        health_work_error(&error),
        Some(HealthWorkError::ResourceExhausted)
    );
    let error = store
        .health_range_plan(
            &identity,
            &HealthRangeLimits {
                planner_rows: 8,
                ..limits(SMALL_RANGE_BUDGET)
            },
            &mut || false,
        )
        .unwrap_err();
    assert_eq!(
        health_work_error(&error),
        Some(HealthWorkError::ResourceExhausted)
    );
    let error = store
        .health_range_plan(&identity, &limits(SMALL_RANGE_BUDGET), &mut || true)
        .unwrap_err();
    assert_eq!(health_work_error(&error), Some(HealthWorkError::Cancelled));
    Ok(())
}

/// The site-target projection is part of the planner's bounded work: it is
/// charged row by row against `planner_rows`, and a projection that cannot
/// fit is dropped instead of being left behind for later requests.
#[test]
fn planner_projection_is_charged_to_the_planner_budget_and_dropped_on_exhaustion() -> Result<()> {
    let temporary = tempfile::tempdir()?;
    let fixture = generate(temporary.path(), &HealthRangeFixtureShape::small())?;
    let reference_store = open(&fixture)?;
    let plan = plan_for(&reference_store, &fixture, SMALL_RANGE_BUDGET)?;
    let site_targets = plan.stats.site_targets;
    // The aggregate rows before the projection are one per node kind plus a
    // handful of counts; the projection must be the larger part so that a
    // budget of exactly `site_targets` rows is exhausted inside it.
    let aggregate_rows_upper_bound = plan.stats.nodes_by_kind.len() as u64 + 8;
    assert!(site_targets > aggregate_rows_upper_bound, "{plan:?}");
    let range = plan.ranges.first().context("at least one range")?;
    let mut reference_budget = CountingHealthWorkBudget::new(u64::MAX);
    let reference_load = reference_store.load_health_range(&plan, range, &mut reference_budget)?;
    assert_eq!(reference_load.work_used, reference_budget.used());

    // A fresh connection has no projection; planning under `site_targets`
    // rows passes the aggregates and must fail while projecting.
    let store = open(&fixture)?;
    let identity = identity(&store, &fixture)?;
    let error = store
        .health_range_plan(
            &identity,
            &HealthRangeLimits {
                planner_rows: site_targets,
                ..limits(SMALL_RANGE_BUDGET)
            },
            &mut || false,
        )
        .unwrap_err();
    assert_eq!(
        health_work_error(&error),
        Some(HealthWorkError::ResourceExhausted)
    );

    // Nothing was left behind: the range loader has to rebuild the projection
    // on this connection and is charged exactly its rows for doing so; the
    // second load reuses it and costs the same as on the reference connection.
    let mut rebuilt_budget = CountingHealthWorkBudget::new(u64::MAX);
    let rebuilt = store.load_health_range(&plan, range, &mut rebuilt_budget)?;
    assert_eq!(rebuilt.work_used, reference_load.work_used + site_targets);
    assert_eq!(rebuilt.subjects, reference_load.subjects);
    assert_eq!(rebuilt.inbound_edges, reference_load.inbound_edges);
    assert_eq!(rebuilt.inbound_sites, reference_load.inbound_sites);
    let mut reused_budget = CountingHealthWorkBudget::new(u64::MAX);
    let reused = store.load_health_range(&plan, range, &mut reused_budget)?;
    assert_eq!(reused.work_used, reference_load.work_used);

    // A reused projection is still accounted for by the planner, so a plan on
    // this connection reports the same work and digest as the reference plan.
    let replanned = plan_for(&store, &fixture, SMALL_RANGE_BUDGET)?;
    assert_eq!(replanned.planner_work_used, plan.planner_work_used);
    assert_eq!(replanned.plan_digest, plan.plan_digest);

    // A loader budget smaller than the projection fails closed before any
    // range row is read.
    let cold = open(&fixture)?;
    let mut tiny = CountingHealthWorkBudget::new(site_targets - 1);
    let error = cold.load_health_range(&plan, range, &mut tiny).unwrap_err();
    assert_eq!(
        health_work_error(&error),
        Some(HealthWorkError::ResourceExhausted)
    );
    assert_eq!(tiny.used(), site_targets - 1);
    Ok(())
}

#[test]
fn range_and_global_loaders_charge_their_own_budgets() -> Result<()> {
    let temporary = tempfile::tempdir()?;
    let fixture = generate(temporary.path(), &HealthRangeFixtureShape::small())?;
    let store = open(&fixture)?;
    let plan = plan_for(&store, &fixture, SMALL_RANGE_BUDGET)?;

    let mut exhausted = CountingHealthWorkBudget::new(1);
    let error = store
        .load_health_global_context(&plan, &mut exhausted)
        .unwrap_err();
    assert_eq!(
        health_work_error(&error),
        Some(HealthWorkError::ResourceExhausted)
    );
    let mut generous = CountingHealthWorkBudget::new(u64::MAX);
    let global = store.load_health_global_context(&plan, &mut generous)?;
    assert!(global.work_used > 1);
    assert_eq!(generous.used(), global.work_used);
    assert_eq!(global.profiles.len(), fixture.shape.profiles);
    assert_eq!(global.go_module_nodes.len(), fixture.shape.packages);
    assert_eq!(global.scan.id, fixture.scan_id);
    // The global context materializes only the edges that target Go modules
    // (the package imports), never subjects or their inbound edges.
    assert_eq!(
        global.go_package_edges.len(),
        fixture.shape.packages.saturating_sub(1) * fixture.shape.files * fixture.shape.profiles
    );
    assert!(
        global
            .go_package_edges
            .iter()
            .all(|edge| edge.kind == "imports")
    );

    let range = &plan.ranges[0];
    let mut exhausted = CountingHealthWorkBudget::new(1);
    let error = store
        .load_health_range(&plan, range, &mut exhausted)
        .unwrap_err();
    assert_eq!(
        health_work_error(&error),
        Some(HealthWorkError::ResourceExhausted)
    );
    let mut generous = CountingHealthWorkBudget::new(u64::MAX);
    let input = store.load_health_range(&plan, range, &mut generous)?;
    assert_eq!(input.subjects.len() as u64, range.subject_count);
    assert_eq!(input.inbound_edges.len() as u64, range.inbound_edge_count);
    assert!(
        input
            .subjects
            .iter()
            .all(|node| node.id >= range.first_subject_id && node.id <= range.last_subject_id)
    );
    assert!(input.inbound_edges.iter().all(|edge| {
        edge.target >= range.first_subject_id && edge.target <= range.last_subject_id
    }));
    assert!(input.inbound_sites.iter().all(|site| {
        site.target_ids
            .iter()
            .any(|id| id >= &range.first_subject_id && id <= &range.last_subject_id)
    }));
    assert_eq!(generous.used(), input.work_used);

    let identity = identity(&store, &fixture)?;
    let mut exhausted = CountingHealthWorkBudget::new(1);
    let error = store
        .load_health_dependency_input(&identity, &mut exhausted)
        .unwrap_err();
    assert_eq!(
        health_work_error(&error),
        Some(HealthWorkError::ResourceExhausted)
    );
    let mut generous = CountingHealthWorkBudget::new(u64::MAX);
    let (projection, work) = store.load_health_dependency_input(&identity, &mut generous)?;
    assert_eq!(work, generous.used());
    assert!(projection.evidence.is_empty());
    assert!(projection.diagnostics.is_empty());
    assert_eq!(projection.edges.len() as u64, fixture.edges);
    Ok(())
}

// --- Cross-range usage and differential equality ---------------------------

#[test]
fn symbol_used_only_from_a_later_range_is_not_reported() -> Result<()> {
    let temporary = tempfile::tempdir()?;
    let shape = HealthRangeFixtureShape::small().with_caller_after_callee(true);
    let fixture = generate(temporary.path(), &shape)?;
    let store = open(&fixture)?;
    // Small enough that the eight files alone span several ranges.
    const BUDGET: u64 = 120;
    let plan = plan_for(&store, &fixture, BUDGET)?;
    assert!(plan.ranges.len() >= 4, "{} ranges", plan.ranges.len());

    // Package 0 calls package 1; with reversed ordering the caller ids sort
    // after the callee ids, so the callee's range is analysed first.
    let callee = symbol_id(&shape, 1, 0, 0);
    let caller = symbol_id(&shape, 0, 0, 0);
    assert!(symbol_is_called(&shape, 1, 0));
    let callee_range = range_of(&plan, &callee).expect("callee range");
    let caller_range = range_of(&plan, &caller).expect("caller range");
    assert!(
        callee_range.index < caller_range.index,
        "{callee_range:?} {caller_range:?}"
    );
    // Files of package 1 are imported from package 0 (also a later range).
    let imported_file = file_id(&shape, 1, 0);
    let importing_file = file_id(&shape, 0, 0);
    assert!(
        range_of(&plan, &imported_file).unwrap().index
            < range_of(&plan, &importing_file).unwrap().index
    );

    let outcome = ranged(&store, &fixture, BUDGET, RangeOrder::Forward, false, None)?;
    assert_eq!(outcome.diagnostics.mode, HealthExecutionMode::Ranged);
    assert_eq!(
        outcome.diagnostics.ranges.total,
        plan.ranges.len() as u32 + outcome.diagnostics.ranges.resplit
    );
    assert_eq!(
        outcome.diagnostics.ranges.completed,
        outcome.diagnostics.ranges.total
    );
    let reported = subject_ids(&outcome.findings);
    assert!(
        !reported.contains(&callee),
        "callee used from a later range was reported"
    );
    assert!(!reported.contains(&imported_file));
    assert!(
        reported.contains(&importing_file),
        "package 0 files are never imported"
    );
    assert_expected_unused(&fixture, &outcome.findings);
    assert_eq!(outcome.findings, whole_snapshot_findings(&fixture)?);

    // The mirror image: callers sort before callees.
    let forward = generate(
        &temporary.path().join("forward"),
        &HealthRangeFixtureShape::small(),
    )?;
    let store = open(&forward)?;
    let plan = plan_for(&store, &forward, BUDGET)?;
    let callee = symbol_id(&forward.shape, 1, 0, 0);
    let caller = symbol_id(&forward.shape, 0, 0, 0);
    assert!(range_of(&plan, &caller).unwrap().index < range_of(&plan, &callee).unwrap().index);
    let outcome = ranged(&store, &forward, BUDGET, RangeOrder::Forward, false, None)?;
    assert!(!subject_ids(&outcome.findings).contains(&callee));
    assert_eq!(outcome.findings, whole_snapshot_findings(&forward)?);
    Ok(())
}

#[test]
fn ranged_findings_equal_whole_snapshot_findings_on_every_public_shape() -> Result<()> {
    let temporary = tempfile::tempdir()?;
    let shapes = [
        ("small", HealthRangeFixtureShape::small()),
        (
            "later-range-callers",
            HealthRangeFixtureShape::small().with_caller_after_callee(true),
        ),
        (
            "cycle",
            HealthRangeFixtureShape::small().with_mutual_import_cycle(true),
        ),
        (
            "two-modules",
            HealthRangeFixtureShape::small().with_same_path_two_modules(true),
        ),
        (
            "dynamic",
            HealthRangeFixtureShape::small().with_dynamic_import_site(true),
        ),
        (
            "incomplete",
            HealthRangeFixtureShape::small().with_incomplete_unit(true),
        ),
        (
            "missing-profile",
            HealthRangeFixtureShape::small()
                .with_profiles(3)
                .with_caller_after_callee(true),
        ),
    ];
    for (name, shape) in shapes {
        let fixture = generate(&temporary.path().join(name), &shape)?;
        let expected = whole_snapshot_findings(&fixture)?;
        assert!(!expected.is_empty(), "{name}: control has findings");
        if name == "dynamic" {
            let target = symbol_id(&shape, 1, 0, shape.symbols - 1);
            let finding = expected
                .iter()
                .find(|finding| finding.subject_id == target)
                .expect("heuristic dynamic usage keeps the finding");
            assert_ne!(finding.confidence, Confidence::Confirmed);
            assert!(
                finding
                    .blockers
                    .iter()
                    .any(|blocker| blocker.kind == BlockerKind::DynamicLoading)
            );
        }
        let store = open(&fixture)?;
        for per_range_work in [SMALL_RANGE_BUDGET, 2_000, u64::from(u32::MAX)] {
            let outcome = ranged(
                &store,
                &fixture,
                per_range_work,
                RangeOrder::Forward,
                false,
                None,
            )
            .unwrap_or_else(|error| panic!("{name} @ {per_range_work}: {error}"));
            assert_eq!(outcome.findings, expected, "{name} @ {per_range_work}");
            assert!(!outcome.diagnostics.partial);
            assert_eq!(outcome.diagnostics.ranges.failed, 0);
            assert_eq!(outcome.diagnostics.ranges.interrupted, 0);
            assert_eq!(
                outcome.diagnostics.ranges.completed,
                outcome.diagnostics.ranges.total
            );
            assert!(
                outcome.diagnostics.work.ranges_max <= per_range_work,
                "{name} @ {per_range_work}: {:?}",
                outcome.diagnostics.work
            );
            assert_eq!(outcome.scan.id, fixture.scan_id);
        }
        // With the small budget the fixture really is split.
        let split = ranged(
            &store,
            &fixture,
            SMALL_RANGE_BUDGET,
            RangeOrder::Forward,
            false,
            None,
        )
        .expect("split run");
        assert!(
            split.diagnostics.ranges.total > 1,
            "{name}: {:?}",
            split.diagnostics.ranges
        );
    }
    Ok(())
}

#[test]
fn incomplete_analysis_units_keep_every_ranged_finding_unconfirmed() -> Result<()> {
    let temporary = tempfile::tempdir()?;
    let complete = generate(
        &temporary.path().join("complete"),
        &HealthRangeFixtureShape::small(),
    )?;
    let incomplete = generate(
        &temporary.path().join("incomplete"),
        &HealthRangeFixtureShape::small().with_incomplete_unit(true),
    )?;
    let store = open(&complete)?;
    let confirmed = ranged(
        &store,
        &complete,
        SMALL_RANGE_BUDGET,
        RangeOrder::Forward,
        false,
        None,
    )?;
    assert!(
        confirmed
            .findings
            .iter()
            .any(|finding| finding.confidence == Confidence::Confirmed),
        "{:?}",
        counts_by_confidence(&confirmed.findings)
    );
    let store = open(&incomplete)?;
    let outcome = ranged(
        &store,
        &incomplete,
        SMALL_RANGE_BUDGET,
        RangeOrder::Forward,
        false,
        None,
    )?;
    assert_eq!(
        subject_ids(&outcome.findings),
        subject_ids(&confirmed.findings)
    );
    for finding in &outcome.findings {
        assert_ne!(finding.confidence, Confidence::Confirmed, "{}", finding.id);
        assert!(
            finding
                .blockers
                .iter()
                .any(|blocker| blocker.kind == BlockerKind::IncompleteCoverage),
            "{}",
            finding.id
        );
    }
    assert_eq!(outcome.findings, whole_snapshot_findings(&incomplete)?);
    Ok(())
}

// --- Determinism: order, interruption, resume --------------------------------

#[test]
fn range_order_permutations_produce_identical_findings() -> Result<()> {
    let temporary = tempfile::tempdir()?;
    let fixture = generate(
        temporary.path(),
        &HealthRangeFixtureShape::small().with_caller_after_callee(true),
    )?;
    let store = open(&fixture)?;
    let forward = ranged(
        &store,
        &fixture,
        SMALL_RANGE_BUDGET,
        RangeOrder::Forward,
        false,
        None,
    )?;
    assert!(forward.diagnostics.ranges.total > 1);
    for order in [
        RangeOrder::Reverse,
        RangeOrder::Seeded(1),
        RangeOrder::Seeded(0xDEAD_BEEF),
        RangeOrder::Seeded(u64::MAX),
    ] {
        let permuted = ranged(&store, &fixture, SMALL_RANGE_BUDGET, order, false, None)?;
        assert_eq!(permuted.findings, forward.findings, "{order:?}");
        assert_eq!(
            permuted.diagnostics.plan_digest,
            forward.diagnostics.plan_digest
        );
        assert_eq!(permuted.diagnostics.ranges, forward.diagnostics.ranges);
        assert_eq!(
            permuted.diagnostics.work.ranges_total,
            forward.diagnostics.work.ranges_total
        );
    }
    assert_eq!(forward.findings, whole_snapshot_findings(&fixture)?);
    Ok(())
}

/// Cancel after `after` ranges completed in this run; `progress` and the
/// cancellation check share one counter.
fn interrupt_after(
    store: &Store,
    fixture: &HealthRangeFixture,
    after: u32,
    checkpoints: &HealthRangeCheckpointStore,
) -> Result<(Result<RangedUnusedOutcome, RangedHealthError>, u32)> {
    let identity = identity(store, fixture)?;
    let computed = Cell::new(0_u32);
    let mut progress = |progress: depgraph_core::health::ranged::HealthRangeProgress<'_>| {
        if !progress.reused {
            computed.set(computed.get() + 1);
        }
    };
    let outcome = analyze_unused_ranged(
        store,
        &identity,
        RangedUnusedOptions {
            limits: limits(SMALL_RANGE_BUDGET),
            maximum_findings: MAX_HEALTH_FINDINGS,
            allow_partial: false,
            order: RangeOrder::Forward,
            checkpoints: Some(checkpoints.clone()),
            progress: Some(&mut progress),
        },
        || computed.get() >= after,
    );
    Ok((outcome, computed.get()))
}

#[test]
fn interrupt_after_each_range_then_resume_matches_the_uninterrupted_run() -> Result<()> {
    let temporary = tempfile::tempdir()?;
    let fixture = generate(
        temporary.path(),
        &HealthRangeFixtureShape::small().with_caller_after_callee(true),
    )?;
    let store = open(&fixture)?;
    let expected = ranged(
        &store,
        &fixture,
        SMALL_RANGE_BUDGET,
        RangeOrder::Forward,
        false,
        None,
    )?;
    let total = expected.diagnostics.ranges.total;
    assert!(total >= 4, "{total} ranges");
    assert!(!expected.diagnostics.checkpoints.enabled);

    for k in 1..total {
        let checkpoint_dir = temporary.path().join(format!("checkpoints-{k}"));
        std::fs::create_dir_all(&checkpoint_dir)?;
        let checkpoint_store = checkpoint_dir.join("depgraph.sqlite");
        std::fs::write(&checkpoint_store, b"")?;
        let checkpoints = HealthRangeCheckpointStore::open(&checkpoint_store, 64 * 1024 * 1024)?;

        let (interrupted, computed) = interrupt_after(&store, &fixture, k, &checkpoints)?;
        let failure = match interrupted {
            Err(RangedHealthError::Analysis(failure)) => failure,
            Err(other) => panic!("k={k}: expected a cancelled failure, got {other}"),
            Ok(_) => panic!("k={k}: expected a cancelled failure, got a collection"),
        };
        assert_eq!(failure.error, HealthAnalysisError::Cancelled, "k={k}");
        assert_eq!(computed, k, "k={k}");
        assert_eq!(failure.diagnostics.ranges.completed, k, "k={k}");
        assert_eq!(failure.diagnostics.checkpoints.written, k, "k={k}");
        assert!(failure.diagnostics.ranges.interrupted >= 1, "k={k}");
        assert_eq!(
            failure.diagnostics.ranges.completed + failure.diagnostics.ranges.interrupted,
            failure.diagnostics.ranges.total,
            "k={k}: {:?}",
            failure.diagnostics.ranges
        );
        assert!(!failure.diagnostics.partial);

        let resumed = ranged(
            &store,
            &fixture,
            SMALL_RANGE_BUDGET,
            RangeOrder::Forward,
            false,
            Some(checkpoints.clone()),
        )
        .unwrap_or_else(|error| panic!("k={k}: resume failed: {error}"));
        assert_eq!(resumed.findings, expected.findings, "k={k}");
        assert_eq!(resumed.diagnostics.ranges.reused, k, "k={k}");
        assert_eq!(resumed.diagnostics.checkpoints.reused, k, "k={k}");
        assert_eq!(resumed.diagnostics.ranges.completed, total, "k={k}");
        assert_eq!(resumed.diagnostics.ranges.total, total, "k={k}");
        // Only the ranges computed now are charged to this run.
        assert!(resumed.diagnostics.work.ranges_total < expected.diagnostics.work.ranges_total);

        // A third run reuses everything and still converges.
        let warm = ranged(
            &store,
            &fixture,
            SMALL_RANGE_BUDGET,
            RangeOrder::Reverse,
            false,
            Some(checkpoints),
        )?;
        assert_eq!(warm.findings, expected.findings, "k={k}");
        assert_eq!(warm.diagnostics.ranges.reused, total, "k={k}");
        assert_eq!(warm.diagnostics.work.ranges_total, 0, "k={k}");
    }
    Ok(())
}

#[test]
fn foreign_or_stale_checkpoints_are_misses() -> Result<()> {
    let temporary = tempfile::tempdir()?;
    let fixture = generate(
        &temporary.path().join("a"),
        &HealthRangeFixtureShape::small(),
    )?;
    let other = generate(
        &temporary.path().join("b"),
        &HealthRangeFixtureShape::small().with_mutual_import_cycle(true),
    )?;
    let checkpoint_store = temporary.path().join("shared.sqlite");
    std::fs::write(&checkpoint_store, b"")?;
    let checkpoints = HealthRangeCheckpointStore::open(&checkpoint_store, 64 * 1024 * 1024)?;

    let store = open(&fixture)?;
    let first = ranged(
        &store,
        &fixture,
        SMALL_RANGE_BUDGET,
        RangeOrder::Forward,
        false,
        Some(checkpoints.clone()),
    )?;
    assert_eq!(
        first.diagnostics.checkpoints.written,
        first.diagnostics.ranges.total
    );
    assert_eq!(first.diagnostics.ranges.reused, 0);

    // A different graph (different plan digest) sees no hits.
    let other_store = open(&other)?;
    let second = ranged(
        &other_store,
        &other,
        SMALL_RANGE_BUDGET,
        RangeOrder::Forward,
        false,
        Some(checkpoints.clone()),
    )?;
    assert_eq!(second.diagnostics.ranges.reused, 0);
    assert_eq!(second.findings, whole_snapshot_findings(&other)?);

    // A different budget (different plan) sees no hits either.
    let third = ranged(
        &store,
        &fixture,
        SMALL_RANGE_BUDGET * 2,
        RangeOrder::Forward,
        false,
        Some(checkpoints.clone()),
    )?;
    assert_eq!(third.diagnostics.ranges.reused, 0);
    assert_eq!(third.findings, first.findings);

    // Corrupting a checkpoint file makes it a miss, not a wrong answer.
    for entry in std::fs::read_dir(checkpoints.directory())? {
        let path = entry?.path();
        let mut bytes = std::fs::read(&path)?;
        if let Some(byte) = bytes.iter_mut().rev().nth(8) {
            *byte ^= 0x55;
        }
        std::fs::write(&path, bytes)?;
    }
    let fourth = ranged(
        &store,
        &fixture,
        SMALL_RANGE_BUDGET,
        RangeOrder::Forward,
        false,
        Some(checkpoints),
    )?;
    assert_eq!(fourth.diagnostics.ranges.reused, 0);
    assert_eq!(fourth.findings, first.findings);
    Ok(())
}

#[test]
fn unwritable_checkpoint_directory_degrades_to_no_checkpoints() -> Result<()> {
    let temporary = tempfile::tempdir()?;
    let fixture = generate(temporary.path(), &HealthRangeFixtureShape::small())?;
    let store = open(&fixture)?;
    let blocked = temporary.path().join("blocked");
    std::fs::create_dir_all(&blocked)?;
    std::fs::write(blocked.join(".depgraph"), b"not a directory")?;
    let store_path = blocked.join("depgraph.sqlite");
    std::fs::write(&store_path, b"")?;
    assert!(HealthRangeCheckpointStore::open(&store_path, 1024).is_err());

    // A checkpoint store whose size bound is too small writes nothing but the
    // analysis still completes.
    let tiny_root = temporary.path().join("tiny");
    std::fs::create_dir_all(&tiny_root)?;
    let tiny_store = tiny_root.join("depgraph.sqlite");
    std::fs::write(&tiny_store, b"")?;
    let tiny = HealthRangeCheckpointStore::open(&tiny_store, 16)?;
    let outcome = ranged(
        &store,
        &fixture,
        SMALL_RANGE_BUDGET,
        RangeOrder::Forward,
        false,
        Some(tiny),
    )?;
    assert_eq!(outcome.diagnostics.checkpoints.written, 0);
    assert_eq!(
        outcome.diagnostics.checkpoints.write_failures,
        outcome.diagnostics.ranges.total
    );
    assert_eq!(outcome.findings, whole_snapshot_findings(&fixture)?);
    Ok(())
}

// --- Over-limit, re-split, failure, partial view ----------------------------

#[test]
fn whole_graph_over_the_budget_completes_in_ranges_under_the_same_budget() -> Result<()> {
    let temporary = tempfile::tempdir()?;
    let fixture = generate(
        temporary.path(),
        &HealthRangeFixtureShape::small().with_caller_after_callee(true),
    )?;
    let store = open(&fixture)?;
    let snapshot = store.load_completed_snapshot(&fixture.snapshot_id)?;
    let budget = SMALL_RANGE_BUDGET as usize;
    // Control: the whole-snapshot analyzer cannot finish under one budget.
    assert_eq!(
        analyze_unused_cancellable(&snapshot, MAX_HEALTH_FINDINGS, budget, || false),
        Err(HealthAnalysisError::ResourceExhausted)
    );
    // The ranged scheduler finishes with every phase under the same budget.
    let outcome = ranged(
        &store,
        &fixture,
        SMALL_RANGE_BUDGET,
        RangeOrder::Forward,
        false,
        None,
    )?;
    assert!(outcome.diagnostics.work.ranges_total > SMALL_RANGE_BUDGET);
    assert!(outcome.diagnostics.work.ranges_max <= SMALL_RANGE_BUDGET);
    assert!(outcome.diagnostics.work.global_context <= SMALL_RANGE_BUDGET);
    assert_eq!(outcome.diagnostics.work.range_limit, SMALL_RANGE_BUDGET);
    assert_eq!(
        outcome.findings,
        analyze_unused_cancellable(&snapshot, MAX_HEALTH_FINDINGS, usize::MAX, || false)?
    );
    Ok(())
}

#[test]
fn overrunning_range_is_resplit_and_a_hub_subject_fails_closed() -> Result<()> {
    let temporary = tempfile::tempdir()?;
    let shape = HealthRangeFixtureShape::small().with_hub_symbol(true);
    let fixture = generate(temporary.path(), &shape)?;
    let store = open(&fixture)?;
    let expected = whole_snapshot_findings(&fixture)?;

    // A budget the planner's estimate satisfies but the hub's real inbound
    // side overruns: the range is split until the hub stands alone, and the
    // remaining subjects still complete.
    let hub = symbol_id(&shape, 0, 0, 0);
    let generous = ranged(&store, &fixture, 4_000, RangeOrder::Forward, false, None)?;
    assert_eq!(generous.findings, expected);
    let hub_work = generous.diagnostics.work.ranges_max;
    assert!(hub_work > SMALL_RANGE_BUDGET, "hub range work {hub_work}");

    // Under the small budget the hub's range cannot complete even alone.
    let failed = ranged(
        &store,
        &fixture,
        SMALL_RANGE_BUDGET,
        RangeOrder::Forward,
        false,
        None,
    );
    let failure = match failed {
        Err(RangedHealthError::Analysis(failure)) => failure,
        Err(other) => panic!("expected a bounded-work failure, got {other}"),
        Ok(_) => panic!("expected a bounded-work failure, got a collection"),
    };
    assert_eq!(failure.error, HealthAnalysisError::ResourceExhausted);
    assert!(
        failure.diagnostics.ranges.resplit >= 1,
        "{:?}",
        failure.diagnostics.ranges
    );
    assert_eq!(failure.diagnostics.ranges.failed, 1);
    assert!(!failure.diagnostics.partial);

    // The partial view returns the completed ranges, demoted.
    let partial = ranged(
        &store,
        &fixture,
        SMALL_RANGE_BUDGET,
        RangeOrder::Forward,
        true,
        None,
    )?;
    assert!(partial.diagnostics.partial);
    assert_eq!(partial.diagnostics.ranges.failed, 1);
    assert_eq!(partial.diagnostics.ranges.interrupted, 0);
    assert!(partial.diagnostics.ranges.completed >= 1);
    assert!(partial.diagnostics.partial_range_status().is_some());
    assert!(!partial.findings.is_empty());
    assert!(partial.findings.iter().all(|finding| {
        finding.confidence == Confidence::Indeterminate
            && finding.blockers.iter().any(|blocker| {
                blocker.kind == BlockerKind::IncompleteCoverage
                    && blocker.detail.contains("health ranges were not analysed")
            })
    }));
    // Nothing in the partial view claims a subject the failed range owns, and
    // every reported subject is a real finding of the complete collection (the
    // hub itself is used by everyone, so its failed range withholds no finding
    // here; the demotion is what keeps the set from reading as complete).
    let expected_ids = subject_ids(&expected);
    for finding in &partial.findings {
        assert_ne!(finding.subject_id, hub);
        assert!(
            expected_ids.contains(&finding.subject_id),
            "{}",
            finding.subject_id
        );
    }
    assert!(partial.findings.len() <= expected.len());
    let demoted = partial
        .findings
        .iter()
        .map(|finding| finding.fingerprint.clone())
        .collect::<BTreeSet<_>>();
    let exact = expected
        .iter()
        .map(|finding| finding.fingerprint.clone())
        .collect::<BTreeSet<_>>();
    assert!(
        demoted.is_disjoint(&exact),
        "partial fingerprints must differ"
    );
    Ok(())
}

// --- Service contract -------------------------------------------------------

fn service(fixture: &HealthRangeFixture) -> Result<DepgraphService> {
    Ok(DepgraphService::new(DepgraphServiceConfig::new(
        &fixture.root,
        &fixture.store_path,
        DepgraphCapabilitySet::read_only(),
        DepgraphServiceLimits::default(),
    )?))
}

#[test]
fn service_health_uses_the_ranged_path_and_matches_the_whole_snapshot_control() -> Result<()> {
    let temporary = tempfile::tempdir()?;
    let fixture = generate(
        temporary.path(),
        &HealthRangeFixtureShape::small().with_caller_after_callee(true),
    )?;
    let service = service(&fixture)?;
    let cancellation = CancellationToken::new();
    let mut request =
        service.start_snapshot_request_at_cancellable(&SnapshotLocator::Current, &cancellation)?;
    assert_eq!(request.snapshot_id().as_str(), fixture.snapshot_id);

    let summary = service.health_summary(
        &mut request,
        &HealthSummaryRequest::try_new(None)?,
        &cancellation,
    )?;
    assert!(!summary.partial());
    let diagnostics = summary.diagnostics();
    assert_eq!(diagnostics.mode, HealthExecutionMode::Ranged);
    assert_eq!(
        diagnostics.layers,
        vec![HealthLayer::Scan {
            scan_id: fixture.scan_id.clone()
        }]
    );
    assert!(diagnostics.plan_digest.is_some());
    assert_eq!(diagnostics.ranges.completed, diagnostics.ranges.total);
    assert_eq!(
        diagnostics.ranges.failed + diagnostics.ranges.interrupted,
        0
    );
    assert_eq!(
        diagnostics.work.range_limit,
        health_range_limits().per_range_work
    );
    assert!(diagnostics.work.planner > 0);
    assert!(diagnostics.work.global_context > 0);
    assert!(diagnostics.work.ranges_total > 0);
    assert!(diagnostics.work.ranges_max <= diagnostics.work.range_limit);
    assert!(diagnostics.work.dependencies_load > 0);
    assert!(diagnostics.checkpoints.enabled);
    assert_eq!(diagnostics.checkpoints.written, diagnostics.ranges.total);
    let (files, symbols) = expected_unused_counts(&fixture.shape);
    assert_eq!(summary.counts_by_kind()["unused-file"], files as u64);
    assert_eq!(summary.counts_by_kind()["unused-export"], symbols as u64);

    let findings = service.health_findings(
        &mut request,
        &HealthFindingsRequest::try_new(Vec::new(), Vec::new(), Vec::new(), MAX_HEALTH_FINDINGS)?,
        &cancellation,
    )?;
    assert_eq!(findings.collection_digest(), summary.collection_digest());
    assert_eq!(
        findings.diagnostics().ranges.reused,
        diagnostics.ranges.total
    );
    let unused = findings
        .findings()
        .iter()
        .filter(|finding| {
            matches!(
                finding.kind,
                FindingKind::UnusedFile | FindingKind::UnusedExport | FindingKind::UnusedType
            )
        })
        .cloned()
        .collect::<Vec<_>>();
    assert_eq!(unused, whole_snapshot_findings(&fixture)?);

    // The checkpoint sidecar lives next to the store, never in the repository.
    let sidecar = fixture
        .store_path
        .parent()
        .unwrap()
        .join(".depgraph")
        .join("health-range-checkpoints-v1");
    assert!(sidecar.is_dir());
    assert!(!fixture.root.join(".depgraph").exists());
    Ok(())
}

#[test]
fn service_partial_view_is_opt_in_and_never_shares_a_digest_with_a_complete_collection()
-> Result<()> {
    let temporary = tempfile::tempdir()?;
    let fixture = generate(temporary.path(), &HealthRangeFixtureShape::small())?;
    let service = service(&fixture)?;
    let cancellation = CancellationToken::new();
    let mut request =
        service.start_snapshot_request_at_cancellable(&SnapshotLocator::Current, &cancellation)?;
    let complete = service.health_summary(
        &mut request,
        &HealthSummaryRequest::try_new(None)?.with_allow_partial(true),
        &cancellation,
    )?;
    // Allowing the partial view changes nothing when every range completes.
    assert!(!complete.partial());
    let strict = service.health_summary(
        &mut request,
        &HealthSummaryRequest::try_new(None)?,
        &cancellation,
    )?;
    assert_eq!(complete.collection_digest(), strict.collection_digest());
    assert_eq!(
        complete.counts_by_confidence(),
        strict.counts_by_confidence()
    );

    // A pre-cancelled request fails closed regardless of the partial flag.
    cancellation.cancel();
    assert!(matches!(
        service.health_summary(
            &mut request,
            &HealthSummaryRequest::try_new(None)?.with_allow_partial(true),
            &cancellation,
        ),
        Err(DepgraphServiceError::Cancelled)
    ));
    Ok(())
}

#[test]
fn plan_estimates_bound_the_measured_range_work() -> Result<()> {
    // Calibration guard: on the public shapes the planner's estimate is an
    // upper bound of the measured per-range work, so re-splitting stays the
    // exception (hub-like outliers) rather than the rule.
    let temporary = tempfile::tempdir()?;
    for (name, shape) in [
        ("small", HealthRangeFixtureShape::small()),
        (
            "later",
            HealthRangeFixtureShape::small().with_caller_after_callee(true),
        ),
        (
            "profiles",
            HealthRangeFixtureShape::small().with_profiles(5),
        ),
    ] {
        let fixture = generate(&temporary.path().join(name), &shape)?;
        let store = open(&fixture)?;
        let plan = plan_for(&store, &fixture, SMALL_RANGE_BUDGET)?;
        let outcome = ranged(
            &store,
            &fixture,
            SMALL_RANGE_BUDGET,
            RangeOrder::Forward,
            false,
            None,
        )?;
        assert_eq!(
            outcome.diagnostics.ranges.resplit, 0,
            "{name}: {:?}",
            outcome.diagnostics.ranges
        );
        let estimated = plan
            .ranges
            .iter()
            .map(|range| range.estimated_work)
            .sum::<u64>();
        assert!(
            outcome.diagnostics.work.ranges_total <= estimated,
            "{name}: measured {} > estimated {estimated}",
            outcome.diagnostics.work.ranges_total
        );
    }
    Ok(())
}

#[test]
fn diagnostics_serialize_with_a_stable_shape() -> Result<()> {
    let temporary = tempfile::tempdir()?;
    let fixture = generate(temporary.path(), &HealthRangeFixtureShape::small())?;
    let store = open(&fixture)?;
    let outcome = ranged(
        &store,
        &fixture,
        SMALL_RANGE_BUDGET,
        RangeOrder::Forward,
        false,
        None,
    )?;
    let value = serde_json::to_value(&outcome.diagnostics)?;
    let keys = value
        .as_object()
        .unwrap()
        .keys()
        .cloned()
        .collect::<Vec<_>>();
    let mut expected = vec![
        "mode",
        "plan_digest",
        "layers",
        "ranges",
        "work",
        "checkpoints",
        "partial",
    ];
    if outcome.diagnostics.peak_rss_kib.is_some() {
        expected.push("peak_rss_kib");
    }
    assert_eq!(keys, expected);
    assert_eq!(value["mode"], "ranged");
    assert_eq!(value["layers"][0]["kind"], "scan");
    let back: depgraph_core::health::ranged::HealthRangeDiagnostics =
        serde_json::from_value(value)?;
    assert_eq!(back, outcome.diagnostics);
    Ok(())
}
